//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyMaster
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Companies
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public int Country { get; set; }
        public int BusinessSegmentFK { get; set; }
        public int TypeFK { get; set; }
    
        public virtual BusinessSegments BusinessSegments { get; set; }
        public virtual Countries Countries { get; set; }
        public virtual Types Types { get; set; }
    }
}
